site_name: Análise de Atrasos de Voos em Aeroportos

repo_url: https://github.com/FelipeFreire-gf/SBD2-Airline_Delay_Cause
repo_name: 2025.4-airline-delays
site_description: "Documentação do Projeto de Análise de Atrasos de Voos em Aeroportos dos Estados Unidos"

nav:
  - Home: index.md
  
  - Entrega 0 - Base de Dados:
    - Proposito de Avaliação: pages/entrega0/0.md

  - Entrega 1 - Raw e Silver:
    - Planejamento de Avaliação: pages/entrega1/1.md

  - Entrega 2 - Gold:
    - Descrição da Medição: pages/entrega2/2.md

  - Entrega 3 - Power Bi:
    - Execução da Medição: pages/entrega3/3.md

theme:
  name: material
  language: pt-BR

  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking
  
  palette:
    - scheme: default
      primary: '--md-primary-fg-color'
      accent: '--md-primary-fg-color'
      toggle:
        icon: material/lightbulb-outline
        name: Mude para o tema escuro
        
    - scheme: slate
      primary: '--md-primary-fg-color'
      accent: '--md-primary-fg-color'
      toggle:
        icon: material/lightbulb
        name: Mude para o tema claro

  
  logo: assets/logo.png
  favicon: assets/shawR2.png
  highlightjs: true

extra_css:
  - overrides/styles.css

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences